[package]
name = "learning-rust-in-hebrew-2024-02-25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lints.clippy]
pedantic = "deny"
